server:
  port: 8882

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lucky-journey
    username: root
    password: DZxy0413
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.qq.com
    port: 465
    username: ${MAIL_NAME:1}
    password: ${MAIL_PASSWORD:1}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0


